version: '3.3'

services:
  bot:
    build: .
    command: python bot.py
    env_file:
      - ./.env
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - cache:/data
    restart: always




volumes:
  cache:
